- name: cp all certs to other masters
  slurp:
    src: "{{ certs }}/{{ item }}"
  with_items:
    - apiserver.crt
    - apiserver.key
    - apiserver-kubelet-client.crt
    - apiserver-kubelet-client.key
    - ca.crt
    - ca.key
    - front-proxy-ca.crt
    - front-proxy-ca.key
    - front-proxy-client.crt
    - front-proxy-client.key
    - sa.key
    - sa.pub
  register: cert
  run_once: true
  # delegate_to: "{{ groups['sslhost'][0] }}"